### PR TITLE
Quiet mode

### PR DESCRIPTION
**Pull request by crackcomm**
```bash
VERSION=`go-bumper -patch -quiet` && git add package.json && git commit -m "chore(release): $VERSION"
```

### CODE REVIEW

**Review by stefanoschrs — COMMENTED** [review]
It's a good idea the quiet mode

- I was thinking more of adding a logger library like `op/go-logging` so it will be much easier to change things rather than having an If on every log
- About the return version, it won't work as you thought about I think because it will execute for all the files that it will bump

**Comment by crackcomm** [comment]
It works, I am using it already from my fork :) thanks for a great app :+1:

**Comment by stefanoschrs** [comment]
Nice! Do you mind if I keep only the version and not the quiet mode?

**Comment by crackcomm** [comment]
Anything that fixes this problem, thanks.

**Pull request closed without merging**
